/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TemplatesNameRouteImport } from './routes/templates/$name'
import { Route as ProjectsProjectIdConfigureRouteImport } from './routes/projects/$projectId/configure'
import { Route as ProjectsProjectIdBoardRouteImport } from './routes/projects/$projectId/board'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNameRoute = TemplatesNameRouteImport.update({
  id: '/templates/$name',
  path: '/templates/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdConfigureRoute =
  ProjectsProjectIdConfigureRouteImport.update({
    id: '/projects/$projectId/configure',
    path: '/projects/$projectId/configure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdBoardRoute = ProjectsProjectIdBoardRouteImport.update({
  id: '/projects/$projectId/board',
  path: '/projects/$projectId/board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/sessions': typeof SessionsRoute
  '/templates/$name': typeof TemplatesNameRoute
  '/templates/': typeof TemplatesIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/configure': typeof ProjectsProjectIdConfigureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/sessions': typeof SessionsRoute
  '/templates/$name': typeof TemplatesNameRoute
  '/templates': typeof TemplatesIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/configure': typeof ProjectsProjectIdConfigureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/sessions': typeof SessionsRoute
  '/templates/$name': typeof TemplatesNameRoute
  '/templates/': typeof TemplatesIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/configure': typeof ProjectsProjectIdConfigureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/sessions'
    | '/templates/$name'
    | '/templates/'
    | '/projects/$projectId/board'
    | '/projects/$projectId/configure'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/sessions'
    | '/templates/$name'
    | '/templates'
    | '/projects/$projectId/board'
    | '/projects/$projectId/configure'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/sessions'
    | '/templates/$name'
    | '/templates/'
    | '/projects/$projectId/board'
    | '/projects/$projectId/configure'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  SessionsRoute: typeof SessionsRoute
  TemplatesNameRoute: typeof TemplatesNameRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ProjectsProjectIdBoardRoute: typeof ProjectsProjectIdBoardRoute
  ProjectsProjectIdConfigureRoute: typeof ProjectsProjectIdConfigureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$name': {
      id: '/templates/$name'
      path: '/templates/$name'
      fullPath: '/templates/$name'
      preLoaderRoute: typeof TemplatesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/configure': {
      id: '/projects/$projectId/configure'
      path: '/projects/$projectId/configure'
      fullPath: '/projects/$projectId/configure'
      preLoaderRoute: typeof ProjectsProjectIdConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/board': {
      id: '/projects/$projectId/board'
      path: '/projects/$projectId/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof ProjectsProjectIdBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  SessionsRoute: SessionsRoute,
  TemplatesNameRoute: TemplatesNameRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ProjectsProjectIdBoardRoute: ProjectsProjectIdBoardRoute,
  ProjectsProjectIdConfigureRoute: ProjectsProjectIdConfigureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
